version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"

  web:
    build: .
    command: tail -f /dev/null  # Change this to the proper CMD after setup
    volumes:
      - .:/sample_rails_application
      - /sample_rails_application/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
