apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails
        image: ayushmaansingh/rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        command: ["rails", "server", "-b", "0.0.0.0"]
